# Scalability experiments

## Deepwalk

### BlogCatalog

In [45]:
import scipy.io as sio
import numpy as np
import pandas as pd

In [46]:
# load a .mat file into a numpy array
def load_mat(filename):
    data = sio.loadmat(filename)
    # return data['data']
    return data
    # return data['network']
    # Extract the adjacency matrix

In [47]:
data_np = load_mat('blogcatalog.mat')
data_np = data_np['network']

# Convert the sparse matrix to a dense adjacency matrix
adjmat = data_np.toarray()

print(adjmat)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [53]:
# Also obtain the labels
data_np = load_mat('blogcatalog.mat')
labels_one_hot = data_np['group'].toarray()

print(labels_one_hot.shape)     # (10312, 39)

'''Now we know that the labels are one-hot encoded'''
# labels = np.argmax(labels_one_hot, axis=1)
# print(labels.shape)     # (10312,)
# print(labels)

label_sample = labels_one_hot[100]      # Thus, each node can have multiple labels (indicated by 2 ones in the array)
print(label_sample)


(10312, 39)
[0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
